#!/bin/bash
# Pilot config: Heat shock factor 1 / HSF1 winged-helix / 5D5U
#
# DNA-DUPLEX REGENERATION (2026-07): 5D5U's asymmetric unit deposits ONE HSF1
# protomer + ONE 12-nt DNA strand. That strand (GGTTCTAGAACC) is exactly
# self-complementary; the biological assembly is tetrameric (2 protein + 2 DNA)
# with the duplex + 2nd protein generated by the crystallographic 2-fold
# (oper 2, x,-y,-z). The single ASU strand is NOT a duplex, so DeepPBS
# featurization failed with "helix count problem 0" on every frame.
# Fix: 5d5u.cif now holds the regenerated MONOMER assembly — one protein chain
# over the full 12-bp duplex (strand A + its 2-fold mate, chain D). Original ASU
# preserved as 5d5u_asu_original.cif.
#   Detector on the duplex ref: chainid 2 protein (100 res), chainid 0/1 DNA (12 each).

export TF_NAME="hsf"
export PDB_ID="5d5u"

# PWM (config/deeppbs_pdb_pwms.csv): MA0486.2.jaspar / HSF1_HUMAN.H11MO.0.A.
# Not in the id.txt benchmark - wiring placeholder (unused until Stage 4).
# Same-family benchmark entries (n=3): 5hdn/7dcj HSF1_HUMAN.H11MO.0.A, MA0486.2.
export PWM_LABEL="MA0486.2.jaspar"
export TEST_PWM_FILTER="MA0486|HSF"
export TEST_FILTER_NAME="HSF"

# B2 - Stage 1 ensemble selector: 5d5u_chainB_protein.pdb -> "B" (already run).
export BINDING_CHAIN="B"

# Stage 2 chain layout (0-based cif chainids) for the REGENERATED duplex ref.
# PROTEIN_CHAIN=2 is the HSF1 protomer; DNA_CHAINS="0,1" is the full duplex.
export PROTEIN_CHAIN=2
export DNA_CHAINS="0,1"

# Stage 3 minimization parameters.
export RAMP_STAGES="0.1,0.3,0.5,0.7,1.0"
export STEPS_PER_STAGE=500
export RECOVERY_RAMP_STAGES="0.05,0.1,0.2,0.4,0.7,1.0"
export RECOVERY_STEPS_PER_STAGE=1000

export N_FRAMES=100
export FOLD=0

# export FNAT_FLOOR=0.5
